import type { Metadata } from "next";
import { StPeterProvider } from "st-peter-ui";
//@ts-ignore
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import Footer from "@/components/ui/footer";
import BottomNav from "@/components/ui/bottom-nav";
import ServiceWorkerRegister from "@/components/service-worker";
import { DemoAuthProvider } from "@/components/ui/demo-auth";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "E-store V2",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <title>St. Peter E-Store</title>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
        <link rel="apple-touch-icon" href="/icon-192.png" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />
        <meta name="apple-mobile-web-app-title" content="eStore" />
      </head>
      <body style={{ overflowX: "hidden" }}>
        <ServiceWorkerRegister />
        <StPeterProvider theme="green" font="Open Sans">
          <DemoAuthProvider>
            <Navbar />
            {children}
            <BottomNav />
            <Footer />
          </DemoAuthProvider>
        </StPeterProvider>
      </body>
    </html>
  );
}
